# SERVICE WORKER
service:
    channel: service
    keys:
        public: service-public
        private: service-private

# EDGE WORKER
edge:
    keys:
        public: edge-public
        private: edge-private

# IOT WORKER
iot:
    keys:
        public: iot-public
        private: iot-private