# SERVICE WORKER
service:
    channel: service
    keys:
        public: foo
        private: bar

# EDGE WORKER
edge:
    keys:
        public: biz
        private: baz

# IOT WORKER
iot:
    keys:
        public: biz
        private: baz