# SERVICE WORKER
service:
    keys:
        public: foo
        private: bar
    channels:
        - service
        - edges
        - other

# EDGE WORKER
edge:
    keys:
        public: biz
        private: baz
    channels:
        - edges
        - service