version: '3.4'
services:

    # RABBIT MQ
    rabbitmq:
        image: rabbitmq:3-management-alpine
        restart: always
        ports:
            - 5672:5672
            - 15672:15672

    # # SERVICE WORKER
    # service_worker:
    #     build:
    #         dockerfile: worker.dockerfile
    #         context: .
    #     environment:
    #         - WORKER_TYPE=parser
    #     restart: always
    #     volumes:
    #         - ./tenant-parsers/:/tenant-parsers
    #         - ./ingestion/:/ingestion
    #         - ./workers/:/workers